dist: trusty
language: scala
services:
  - docker
scala:
  - 2.11.12
jdk:
- oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_a1a0961ea86f_key -iv $encrypted_a1a0961ea86f_iv -in service-account.json.enc -out ${HOME}/service-account.json -d
script:
  - sbt test
before_deploy:
  - pip install --user release-manager==0.3.0
deploy:
  - provider: script
    skip_cleanup: true
    script: "./.travis/deploy_template.sh $TRAVIS_TAG"
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: release-manager --config ./.travis/release.yml --check-version --make-version --make-artifact --upload-artifact
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: "./.travis/deploy_docker.sh $TRAVIS_TAG"
    on:
      tags: true
env:
  global:
    - secure: ncodfcWlGupVKH/taFMMmypRhJ2x8VRs2ulo9pW/u7UXSf1lOHDFj/GGAprlBRKq0t1ks1fQGr5MMjlBOTbkCHIUP6o5CzpGGcyClnUBHYtWJreCRiJIJmmHZEw3pzSmtTol2wU4xH7c3R0qqGiVb0OZEz4DZonlcRnkDSrP3BgmO14hBR/kcH9S/xJzc9lwoqOzL6nXjAmPyK/Swvxv9NxigMiqKvwNV5FLfQIWIXuwpcDJFabL9zRzCnppsZn7j/UtVGrowziGwyPTFBzDi6flQOhZg8/tDpKomzbemgvHFm6H8baD1tgtKAOdvjCRxnTExcBdqteAa7ocQg6YaePb0D410yPTaaS5lzH5caT1hBszPdce6ksEpE69jupiXnO0PYo3KcPb4uPGwQfE+qf6hIFC3MNcSe0bY9kc0Xo3cAgjIMzrpfzm41fkY/dIV2yPBZf1m3cSnrQBKpHI+Jbl/mnXX4tvmvwxKJYZ7Crd4cYhihWz1zxmhmJP//kD0iHi6rfLvqZOx0CJSG1aFVpnFKIPQxF4hlDEhm0DwUG4SYPBgJHjI1ZltYIvudHdq1n65UbFtw/mkWhEzWsE2zEFtxkMT3hVXRjUKkkbRacAGKJs0ktu8jUFEtkaNG9RXX0BUlSfccHRBADn9uqz5wXovV8d26nRF06AUl0QGhg=
    - secure: ntwyTd5eTHrdO44pXQjXKJ930qOwpuM1DdYeazpVfjwTTjr0ZMhjCTeyFUN2kVQUi6Tv6tt0nrrMabM4311zLAm3JZ/OrELfPq90hgAYc8wv4z2c+Yo+0YX3IIXvAAtNVUU2+s3WGGCa8/vZmtzLyCXU7X8bO3th36GPae5Bv2jpBe0JLAquyY8j1jT7jX6xOe24I6udyAWzRK9aW27HGc7LgPu8Zp98sgqRYpsZT/SQBCEYYnADj8jldFEdSyeERHR9XmVUZOJzmpFdUs/sYOhpyNl/LhFlthm7w/q2qWWs3qEVSRLU2pQErGSpGqFvoFZ/ojH7+Uhvdwih8OBbrKnDYxU9HRMBCY+aV5RVW3PY4xuG2P3hqKzRI+4YjVQZjfaV4fKu0WgP2Bj3Nw4NMGE6Lx+bQ8iov/kUGWPrbnm/s7tOm0BPfJgwuA4pZ9ngJHNOGfaiFhy+VM8GbciA/V9Yt5C6YxN2Ffpgmrs00p/i7SKEsBFK82MkwTubV7Nv62WrIF/zlbFO0Lj+Bc12uFcROvTFyH4pSJQYc+vZJKkPOblKMh6fpxRyNHtHZCrqULZV4PU4E/fcNBfpItFeS0PGFlzmvimxInexPuvQ9bbEbj09NPxkoicxsWItp31DYaC4/jhzhT37LHutgEPdO+/yZcSwsA16I/WI0PyHqcg=
    - secure: RgOTfPNgF1fPf1LweKCyMW5uxFa09NrR4zCHfPz4cE77YFZoDe/qnKfvKrmnNH6EaXHH6Yqobe0feOwALCXsRmOiHSEwbsbajzUJXnTmtzsMmvrXujgkOt1WnvIViinVeS8aSiIs3WwT2j5NBFSsjWheo9CY3nmnjyS5Ef3r7+YefF5ty60ez8bt5pdJrt39l+nZAkvCEyBP7rSCRNiM5S3Ktm+drJo5AfUF4j3WXaaGzYhjbLhvS9rSyxUX2R1rH/2D4VddvlC/UTOsW8ERkTIwtizgOI9sBkZD02w7Dp7C3wvHnvpZq4JJ1fq7iMLZh7O1LSvrwnJHwOHZO3Qd9IiEzHIlRiRBtvofFdn1xUyrbPFV+ZlLbaiXIxZUmKhdZcr/lA2h5/2pnzFdefT+3Sk7qjcZbZH4j8ICrjr8N20+5W8U18fD8rcx6SekdEdJH6wAK4Yy2JpeLN5FxEao94NMFu7kcux/fSUktMRRzvZo275AeLNF8vfe1xsmLxAnoFlhcAKtzabjsiCn+//CS4tWATpZJrLI4hUJO+JfhHtKBtoevVOyyMM39zfwG7KT3sfzuIC/E7uDLaBfNN6GEpQbYLkiy+W7XMLaKT1UdxR8zrstOW8r4hNZEG07lHa/brpC3182axIlIXT4vZ8/cg7SgLrSEy7aOclvD2zuSvg=
    - secure: anz+CgPzs791QYY4z7Bs1/7+Dx95DdEjg53NTV0Ltnw4kJhzqyjQrBOUOjeOiQ0PBrGokYdmlmN/H7Y5N/0Jms/EUltCgk/jMVKqsg/3yaYfQXYLmglRXdZy5TbDJBWox5wmwfUcFFUEZJ+ZT5asDIFNQtp3MB7TbkhQ4LgM1MFzkxTavfjENIltltaL5HGmJCQT8aOV+dcC3YS3BEddsk8Rj00vnlEL/MaUVEhGktQXJMPYBLFajgFdrOLyLEdiE/bMfShW0YBqXnAXX2+QNF0AdNi90RXk2ejnfgXRwcehCUKYr9h3oUCbFYc8qd9ePSMYM1vOOK8EqAtzgkaVbvvWYL3hU/I3PEdRhfnJo/hqRIRo7XPJn4tjI5p0ml/hb1ScHADdc/meLFA7ZMIhc+ClZjyy+QZyYDNaxmRSHp9jH+F6DoEeu0JT0l+aUSN2ajp2HCCYJIU6RRXx5bvh4F23rjUPosV+oPLf9J0VrpRo18QvHNGOi/djGSzecMoUr1eCdPb6jCbWr643366cFIiOxCOsDRpLquRi6v76o5fUaf+5qMSvt1IlpNuSVkC24qrzRW1xKfh+5u+06cxR5FjgN165AbDOLBqDvanpw1umeeaUrrCpjh37pENJAm5RPzNT6RiM4m7UJlvjMRxbuW3+CDarJdLY2WkUOlYe1pQ=
